[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/post"
  to = "/post.html"
  status = 200

[[redirects]]
  from = "/tracker"
  to = "/tracker.html"
  status = 200

[[redirects]]
  from = "/api/tracker"
  to = "/.netlify/functions/tracker"
  status = 200
